name: Autotools Build
on:
  push:
    branches: [ master ]
defaults:
  run:
    working-directory: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name Checkout
      uses: actions/checkout@v2
      with:
        path: source
    - name: Install zj
      run: |
         mkdir lib
         git clone https://gitlab.com/zxq9/zj.git lib/zj
         cd lib/zj
         ./zmake
         cd ..
         mv zj zj-1.0.5
      working-directory: ${{ github.workspace }}
    - name: Maintainer operations
      run: |
        aclocal
        autoheader
        autoconf
        automake --add-missing
        mkdir ${{ github.workspace }}/build
        echo "::set-env name=ERL_LIBS::${{ github.workspace }}/lib"
      working-directory: source
    - name: Install polymer
      run: |
        yarn global add polymer-cli
        echo "::add-path::$(yarn global bin)"
    - name: Configure
      run: ERLANG_INSTALL_LIB_DIR=${{ github.workspace }}/lib ../source/configure
    - name: Build
      run: make
    - name: Upload edoc
      uses: actions/upload-artifact@v2
      with:
        name: doc
        path: build/doc/
    - name: Build dialyzer PLT
      run: dialyzer --build_plt --apps erts kernel stdlib mnesia inets syntax_tools xmerl zj
      continue-on-error: true
    - name: Make check
      run: make check
      continue-on-error: true
    - name: Upload common_test
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: build/test/log/
    - name: Make release
      run: |
          make install

